Vagrant.configure("2") do |config|

  config.vm.box = "debian/jessie64"
#   config.vm.box = "debian/stretch64"

   config.vm.box_check_update = false

   config.vm.network :private_network, ip: "10.0.0.11"

#    config.vm.network :public_network,ip: "192.168.67.211",bridge: "en0: WLAN (AirPort)"

#   config.vm.network "forwarded_port", guest: 3306, host: 3306

#     config.vm.synced_folder "~/Projects/src...", "/var/www/target...",
#       create: true,
#       owner: "www-data", group: "www-data"

#     config.vm.synced_folder "www/8x", "/var/www/8x",
#       create: true,
#       owner: "www-data", group: "www-data"

   ### nic_type = Am79C970A|Am79C973|82540EM|82543GC|82545EM|virtio]
   config.vm.provider :virtualbox do |vb|
      vb.gui = false
      vb.name = "typo3box"
      vb.linked_clone = true
      vb.cpus = 2
      vb.memory = 2048
      vb.customize ["modifyvm", :id, "--nictype1", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype2", "virtio"]
      vb.customize ["modifyvm", :id, "--nictype3", "virtio"]
  end
  
  config.vm.hostname = "t3b.example.org"
  config.hostsupdater.aliases = [
#       "7x.t3b.example.org",
      "8x.t3b.example.org",
#       "dev-master.t3b.example.org",
      "phpmyadmin.t3b.example.org",
#       "webgrind.t3b.example.org"
  ]



    config.vm.provision "shell", path: "scripts/lamp-jessie.sh"
#     config.vm.provision "shell", path: "scripts/lamp-stretch.sh"

#     config.vm.provision "shell", path: "scripts/7x-host.sh"
    config.vm.provision "shell", path: "scripts/8x-host.sh"
    #config.vm.provision "shell", path: "scripts/devmaster-host.sh"

    config.vm.provision "shell", path: "scripts/phpmyadmin.sh"
#     config.vm.provision "shell", path: "scripts/xdebug.sh"
end